In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression 
print("Setup successful!")

df1 = pd.read_csv('data/Bengaluru_House_Data.csv')
df1.head()

Setup successful!

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
df1.groupby('location')['bath'].agg('count')

location
 Anekal                 1
 Banaswadi              1
 Basavangudi            1
 Bhoganhalli            1
 Devarabeesana Halli    6
                       ..
t.c palya               1
tc.palya                4
vinayakanagar           1
white field,kadugodi    1
whitefiled              1
Name: bath, Length: 1305, dtype: int64

In [5]:
df2 = df1.drop(['location', 'size', 'bath'], axis='columns')
df2.head()

              area_type   availability  society total_sqft  balcony   price
0  Super built-up  Area         19-Dec  Coomee        1056      1.0   39.07
1            Plot  Area  Ready To Move  Theanmp       2600      3.0  120.00
2        Built-up  Area  Ready To Move      NaN       1440      3.0   62.00
3  Super built-up  Area  Ready To Move  Soiewre       1521      1.0   95.00
4  Super built-up  Area  Ready To Move      NaN       1200      1.0   51.00

In [6]:
df2.isnull().sum()

area_type          0
availability       0
society         5502
total_sqft         0
balcony          609
price              0
dtype: int64

In [7]:
df3 = df2.dropna()
df3.isnull().sum()

area_type       0
availability    0
society         0
total_sqft      0
balcony         0
price           0
dtype: int64

In [8]:
df3.shape

(7497, 6)

In [4]:
df4 = df1.dropna()
df4.isnull().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [10]:
df4.shape

(7496, 9)

In [3]:
df4.head()

NameError: name 'df4' is not defined

In [5]:
df5 = df4.drop(['society', 'total_sqft'], axis='columns')
df5.head()

,area_type,availability,location,size,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,5.0,3.0,120.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,3.0,1.0,95.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,2.0,1.0,38.00
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,5.0,3.0,295.00

In [6]:
df6 = df5.dropna()
df6.isnull().sum()

area_type       0
availability    0
location        0
size            0
bath            0
balcony         0
price           0
dtype: int64

In [7]:
df6.head()

,area_type,availability,location,size,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,5.0,3.0,120.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,3.0,1.0,95.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,2.0,1.0,38.00
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,5.0,3.0,295.00

In [15]:
df6['size'].unique()

<StringArray>
[    '2 BHK', '4 Bedroom',     '3 BHK', '3 Bedroom',      '1 RK',     '4 BHK',
     '1 BHK',     '5 BHK',    '11 BHK', '5 Bedroom',     '9 BHK', '2 Bedroom',
     '6 BHK',     '7 BHK', '6 Bedroom']
Length: 15, dtype: str

In [16]:
df6['availability'].unique()

<StringArray>
[       '19-Dec', 'Ready To Move',        '18-Nov',        '17-Oct',
        '21-Dec',        '19-Sep',        '20-Sep',        '18-Mar',
        '18-Apr',        '20-Aug',        '19-Mar',        '17-Sep',
        '17-Aug',        '19-Apr',        '22-Dec',        '18-Aug',
        '19-Jan',        '17-Jul',        '18-Jul',        '18-May',
        '18-Dec',        '21-Jun',        '18-Sep',        '17-May',
        '17-Jun',        '18-Oct',        '21-May',        '20-Dec',
        '18-Jun',        '16-Mar',        '22-Jun',        '17-Dec',
        '21-Feb',        '19-May',        '17-Nov',        '20-Oct',
        '20-Jun',        '18-Feb',        '19-Feb',        '21-Oct',
        '21-Jan',        '17-Mar',        '19-Jun',        '17-Apr',
        '22-May',        '19-Oct',        '21-Jul',        '21-Nov',
        '21-Mar',        '19-Jul',        '20-Jan',        '21-Sep',
        '18-Jan',        '20-Mar',        '19-Nov',        '15-Jun',
        '19-Aug',        '20-May',        '20-Nov',        '20-Jul',
        '20-Feb',        '15-Dec',        '21-Aug',        '16-Oct',
        '22-Nov',        '16-Dec',        '15-Aug',        '17-Jan',
        '16-Nov',        '20-Apr',        '22-Jan',        '16-Jan',
        '17-Feb',        '14-Jul']
Length: 74, dtype: str

In [8]:
df6.head()

,area_type,availability,location,size,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,5.0,3.0,120.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,3.0,1.0,95.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,2.0,1.0,38.00
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,5.0,3.0,295.00

In [9]:
df6['bhk'] = df6['size'].apply( lambda x : int(x.split(' ')))
df6.head()

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [10]:
df6['size'].head(20)

0         2 BHK
1     4 Bedroom
3         3 BHK
5         2 BHK
11    4 Bedroom
12        2 BHK
14    3 Bedroom
15        2 BHK
16        3 BHK
17        3 BHK
18        3 BHK
21        3 BHK
22    4 Bedroom
24         1 RK
26        2 BHK
28        2 BHK
29        3 BHK
30        4 BHK
31        3 BHK
32        3 BHK
Name: size, dtype: str

In [11]:
df6['bhk'] = df6['size'].apply(lambda x: int(x.split(' ')[0]))

In [12]:
df6.head()

,area_type,availability,location,size,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,5.0,3.0,120.00,4
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,3.0,1.0,95.00,3
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,2.0,1.0,38.00,2
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,5.0,3.0,295.00,4

In [13]:
df1.total_sqft.unique()

<StringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '2732',        '3300',        '1310',        '1020',
 ...
        '3124',        '9200',         '613',         '250',        '2395',
 '1020 - 1130',        '2758', '1133 - 1384',         '774',        '4689']
Length: 2117, dtype: str

In [14]:
df1.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00